apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: training-shared
  namespace: distributed-training
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs
  resources:
    requests:
      storage: 10Gi
