apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  name: team-a-local-queue
  namespace: first-ai-project
spec:
  clusterQueue: team-a-cluster-queue
---
apiVersion: kueue.x-k8s.io/v1beta2
kind: LocalQueue
metadata:
  name: team-b-local-queue
  namespace: second-ai-project
spec:
  clusterQueue: team-b-cluster-queue
